services:
  web:
    build:
      context: .
      target: galacto-dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: sh -c 'bundle exec puma -v -b tcp://0.0.0.0:3000'
    stdin_open: true
    tty: true
    user: root
    env_file:
      - .env
    environment:
      - RAILS_ROOT=/app
    depends_on:
      - worker
      - chrome
      - fcrepo
      - fits
      - memcached
      - postgres
      - redis
      - solr
    ports:
      - 3000:3000
      - 9876:9876
    volumes:
      - .:/app
      - ./bin:/app/bin
      - bundle:/app/bundle
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - galacto

  worker:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    entrypoint: worker-entrypoint.sh
    command: sh -c 'bundle exec sidekiq'
    user: root
    env_file:
      - .env
    depends_on:
      - fcrepo
      - fits
      - memcached
      - postgres
      - redis
      - solr
    volumes:
      - .:/app
      - ./bin:/app/bin
      - bundle:/app/bundle
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - galacto

  chrome:
    image: selenium/standalone-chromium:4
    environment:
#      - START_XVFB=false
      - SE_NODE_SESSION_TIMEOUT=800
      - SE_ENABLE_TRACING=false
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
      - SE_BROWSER_ARGS_DISABLE_DSHM=--disable-dev-shm-usage
      - SE_BROWSER_ARGS_HEADLESS=--headless=new
#    logging:
#      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
    ports:
      - "4445:4444"
      - "5960:5900"
    networks:
      - galacto

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=hyrax_user
      - POSTGRES_PASSWORD=hyrax_password
      - POSTGRES_DB=hyrax
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - galacto

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data:cached
    ports:
      - 8080:8080
    networks:
      - galacto

  fits:
    image: ghcr.io/samvera/fitsservlet:1.6.0
    ports:
      - 8080
    networks:
      - galacto

  memcached:
    image: bitnami/memcached
    ports:
      - '11211:11211'
    networks:
      - galacto

  redis:
    image: bitnami/redis:6.2
    env_file:
      - .env
    volumes:
      - redis:/bitnami/redis/data
    networks:
      - galacto

  solr:
    image: solr:8.11
    ports:
      - 8983:8983
    command:
      - sh
      - "-c"
      - "precreate-core hyrax_test /opt/solr/server/configsets/hyraxconf; precreate-core hyrax-valkyrie-test /opt/solr/server/configsets/hyraxconf; precreate-core hyrax-valkyrie-dev /opt/solr/server/configsets/hyraxconf; solr-precreate hyrax /opt/solr/server/configsets/hyraxconf"
    volumes:
      - solr_home:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/hyraxconf
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    networks:
      - galacto

volumes:
  bundle:
  db:
  fcrepo:
  hyrax-derivatives:
  hyrax-uploads:
  rails-public:
  rails-tmp:
  redis:
  solr_home:

networks:
  galacto:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-galacto
