# Requires Docker Compose v2
name: galacto
services:
  app:
    build:
      context: .
    image: ghcr.io/iublibtech/galacto/galacto:latest
    env_file:
      - .docker.env
    volumes:
      - storage:/app/samvera/hyrax-webapp/storage
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    depends_on:
      - redis
      - postgres
      - fcrepo
      - solr
      - fits
    ports:
      - 3000:3000
    command: bundle exec rails s

  worker:
    image: ghcr.io/iublibtech/galacto/galacto:latest
    command: sh -c 'bundle exec sidekiq'
    user: root
    env_file:
      - .docker.env
    depends_on:
      - redis
      - postgres
      - fcrepo
      - solr
      - fits
    volumes:
      - storage:/app/samvera/hyrax-webapp/storage
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp

  postgres:
    image: postgres:15
    env_file:
      - .docker.env
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:6.2
    env_file:
      - .docker.env
    volumes:
      - redis:/bitnami/redis/data

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    env_file:
      - .docker.env
    volumes:
      - fcrepo:/data:cached

  solr:
    image: solr:8.11
    env_file:
      - .docker.env
    command: solr-precreate galacto /opt/solr/server/configsets/hyraxconf
    volumes:
      - solr_home:/var/solr/data
      - ./solr/conf:/opt/solr/server/configsets/hyraxconf:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 524288

  fits:
    image: ghcr.io/samvera/fitsservlet:1.6.0

volumes:
  db:
  redis:
  solr_home:
  storage:
  fcrepo:
  hyrax-derivatives:
  hyrax-uploads:
  rails-public:
  rails-tmp:
