default: &default
  user: <%= Galacto.config[:fedora][:user] %>
  password: <%= Galacto.config[:fedora][:password] %>
  url: <%= Galacto.config[:fedora][:url] %>
  base_path: <%= Galacto.config[:fedora][:base_path] %>
  request:
    timeout: 300
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

