default: &default
  fedora:
    user: fedoraAdmin
    password: fedoraAdmin
    url: http://localhost:8989/rest
    base_path: /galacto-dev
  solr:
    url: http://localhost:8988/solr/galacto-dev
  db:
    adapter: postgresql
    host: localhost
    port: 5437
    database: galacto-dev
    user: galacto_user
    password: galacto_pass
  redis:
    rails:
      url: "redis://127.0.0.1:6379/0"
    cable:
      url: "redis://127.0.0.1:6379/0"
    sidekiq:
      url: "redis://:galacto_valkey@127.0.0.1:6384/0"
  auth:
    cas_host: idp-stg.login.iu.edu
    cas_login_url: /idp/profile/cas/login
    cas_validate_url: /idp/profile/cas/serviceValidate
    cas_logout_url: /idp/profile/cas/logout
    cas_callback_url: /users/auth/cas/callback
  sidekiq:
    # This only signals whether Sidekiq runs locally and to check with OKComputer; doesn't alter Sidekiq config or behavior
    processes_locally: true
    queue_names:
      - important
      - default
      - ingest
      - import # Bulkrax
      - export # Bulkrax
    max_retries: 0
  rails:
    log_level: debug
    mailer:
      host: localhost:3000
      address: 'smtp.gmail.com'
      port: 587
      user_name: 'example@gmail.com'
      password: 'app_password'
      authentication: 'plain'
      raise_delivery_errors: false
      enable_starttls_auto: true
      openssl_verify_mode: 'none'
    serve_static_files: true
    cache:
      store: memory_store
      options:
    active_job:
      queue_adapter: sidekiq
  cantaloupe:
    iiif_server_url: http://localhost:8182/iiif/2/
  #    iiif_server_url: http://localhost:8182/iiif/2/
  derivatives:
    path: <%= Rails.root.join("tmp/derivatives") %>
  fits:
    ch12n_tool: fits_servlet
    fits_servlet_url: http://localhost:8085/fits
  iucat_libraries:
    url: https://iucat.iu.edu/api/library
    api_enabled: true
  analytics:
    enabled: false
    url: //changeme
    site_id: 0
  google_analytics:
    id:
  aws:
    endpoint: http://localhost:9000
    bucket: galacto-dropbox
    access_key_id: galacto-minio
    secret_access_key: Galacto12345
    region: us-east-1
  external_storage:
    url:
    access_key:
    secret_key:
    region: 'us-east-1'
    bucket:
    prefix:
  browse_everything:
    file_system:
      :home: <%= Rails.root.join("staged_files") %>
  airbrake:
    host:
    errbit: false
    project_id:
    project_key:
    proxy:
      enabled: false
      config:
        host:
        port:
        user:
        password:
  rack_profiler:
    enabled: true
  rack_attack:
    enabled: true
    config_key: rack_attack_config-v1
    config_ttl: 60
    throttle_limit: 30
    throttle_period: 60
  ldap:
    enabled: false
    host: ads.iu.edu
    tree: dc=ads,dc=iu,dc=edu
    account_ou: ou=Accounts
    group_ou: ou=BL
    method: simple
    user: dlptech,ou=Accounts,dc=ads,dc=iu,dc=edu
    pass: changeme
    group_roles:
      admin:
        - ESSI-USERS
    default_email_domain: iu.edu
  authorized_ldap_groups:
    - ESSI-USERS
  galacto:
    site_usage: admin # admin or access_only
    allow_dev_login: false
    iiif_host: localhost:3000  # riiif only
    notifier_email: example@test.test
    store_original_files: true
    store_files_as_jp2: true
    store_in_external_storage: false
    kdu_compress_path: '' # set as kdu_compress or opj_compress, or '' to use ImageMagick
    master_file_service_url: http://purl.dlib.indiana.edu/iudl/variations/master
    purl_redirect_url: /concern/works/%s
    purl_validation_regex: '^[a-zA-Z\d\/-]{0,}$'
    skip_derivatives: false
    derivatives_folder: 'staged_files'
    derivatives_type_suffix: true
    derivatives_type_subfolder: true
    derivatives_work_subfolder: true
    ocr_language: [eng]
    ocr_preprocessor_path: <%= Rails.root.join('bin', 'ocr_preprocessor') %>
    create_ocr_files: true
    index_ocr_files: true
    create_word_boundaries: true
    nested_indexer_depth: 5
    allow_pdf_download: false
    link_banners: false
    bagit:
      default_upload_dropbox: <%= Rails.root.join("staged_files/uploaded") %>
      default_bagit_dir: <%= Rails.root.join("staged_files/work_bags") %>
    manifest_builder:
      see_also_hash: # TODO: enable or deprecate
        id: http://metadata.remote.service.url/iucatextract?maximumRecords=1&operation=searchRetrieve&query=cql.serverChoice=%s&recordSchema=marcxml&version=1.1
        format: application/xml
    metadata:
      remote_lookup: http://metadata.remote.service.url
      url: https://purl.dlib.indiana.edu/iudl/iucat/%s
      editable:
        - :identifier
        - :sort_title
        - :responsibility_note
        - :series
        - :creator
        - :published
        - :publication_place
        - :publisher
        - :date_published
        - :physical_description
        - :lccn_call_number
        - :local_call_number
        - :copyright_holder
        - :date_created
        - :subject
        - :alternative_title
        - :digital_date
        - :usage_right
        - :volume_and_issue_no
        - :digital_collection
        - :owning_institution
        - :funding
        - :digital_specifications
        - :author
        - :digital_publisher
      iiif:
        - :date_modified
        - :contributor
        - :subject
        - :series
        - :publisher
        - :language
        - :identifier
        - :date_created
        - :based_near_label
        - :related_url
        - :resource_type
        - :source
        - :rights_statement
        - :holding_location
      profile_log: <%= Rails.root.join('log', 'profile_validation.log') %>
    jp2_recipes:
      default_color: >
        -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
        -jp2_space sRGB
        -double_buffering 10
        -num_threads 1
        -no_weights
        Clevels=6
        Clayers=8
        Cblk=\{64,64\}
        Cuse_sop=yes
        Cuse_eph=yes
        Corder=RPCL
        ORGgen_plt=yes
        ORGtparts=R
        Stiles=\{1024,1024\}
      default_gray: >
        -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
        -jp2_space sLUM
        -double_buffering 10
        -num_threads 1
        -no_weights
        Clevels=6
        Clayers=8
        Cblk=\{64,64\}
        Cuse_sop=yes
        Cuse_eph=yes
        Corder=RPCL
        ORGgen_plt=yes
        ORGtparts=R
        Stiles=\{1024,1024\}
    campus_logos:
      example_collection_type:
        title: Example title
        url: https://example.com
      example_admin_set:
        title: Example title
        url: https://example.com
    homepage_banner: images/homepage_banner.png
    collection_banner_size: "max"
    whitelisted_ingest_dirs: []
    audit_user_key: example@test.test
    batch_user_key: example@test.test
    contact_email: example@test.test
    service_log: <%= Rails.root.join('log', 'file_service.log') %>
  geonames:
    username: dlpierce # change in deployment

development:
  <<: *default

test:
  <<: *default
  fedora:
    user: fedoraAdmin
    password: fedoraAdmin
    url: http://localhost:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
    base_path: /test
  solr:
    url: http://localhost:8985/solr/hydra-test
  db:
    adapter: mysql2
    host: 127.0.0.1
    database: galacto_test
    user: galacto
    password: galacto
  redis:
    rails:
      url: "redis://127.0.0.1:6379/11"
    cable:
      url: "redis://127.0.0.1:6379/10"
    sidekiq:
      url: "redis://127.0.0.1:6379/9"
  cantaloupe:
    iiif_server_url: https://localhost:3000/iiif/2/
  browse_everything:
    file_system:
      :home: <%= Rails.root.join("spec/fixtures") %>
  external_storage:
    url: http://localhost:9000
    access_key: galacto-minio
    secret_key: Galacto12345
    region: us-east-1
    bucket: galacto-test
    prefix: ext-store

production:
  <<: *default
